// Code generated by `yarn themes-generate` (scripts/cli/generateStylexTokenFiles.ts). DO NOT EDIT.

// Theme values that never vary between themes. Generated from createBreakpoints/createTransitions so
// the emitted strings are byte-identical to what Emotion produced.
import * as stylex from '@stylexjs/stylex';

/** `theme.breakpoints.up(key)` → `bp.<key>Up`, `theme.breakpoints.down(key)` → `bp.<key>Down`. */
export const bp = stylex.defineConsts({
  xsUp: '@media (min-width:0px)',
  smUp: '@media (min-width:544px)',
  mdUp: '@media (min-width:769px)',
  lgUp: '@media (min-width:992px)',
  xlUp: '@media (min-width:1200px)',
  xxlUp: '@media (min-width:1440px)',
  xsDown: '@media (max-width:-0.05px)',
  smDown: '@media (max-width:543.95px)',
  mdDown: '@media (max-width:768.95px)',
  lgDown: '@media (max-width:991.95px)',
  xlDown: '@media (max-width:1199.95px)',
  xxlDown: '@media (max-width:1439.95px)',
});

/** `theme.transitions.handleMotion('no-preference')` → `motion.noPreference`, etc. */
export const motion = stylex.defineConsts({
  noPreference: '@media (prefers-reduced-motion: no-preference)',
  reduce: '@media (prefers-reduced-motion: reduce)',
  noPreferenceOrReduce: '@media (prefers-reduced-motion: no-preference),(prefers-reduced-motion: reduce)',
});

/** `theme.transitions.duration.<key>` as a CSS time. */
export const durations = stylex.defineConsts({
  shortest: '150ms',
  shorter: '200ms',
  short: '250ms',
  standard: '300ms',
  complex: '375ms',
  enteringScreen: '225ms',
  leavingScreen: '195ms',
});

/** `theme.transitions.easing.<key>`. */
export const easings = stylex.defineConsts({
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
  easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
});

/** `theme.zIndex.<key>`. */
export const zIndex = stylex.defineConsts({
  activePanel: 999,
  navbarFixed: 1000,
  sidemenu: 1020,
  dropdown: 1030,
  typeahead: 1030,
  tooltip: 1040,
  modalBackdrop: 1050,
  modal: 1060,
  portal: 1061,
});

/** `theme.breakpoints.values.<key>` in px. */
export const breakpointWidths = stylex.defineConsts({
  xs: '0px',
  sm: '544px',
  md: '769px',
  lg: '992px',
  xl: '1200px',
  xxl: '1440px',
});
