// Code generated by `yarn themes-generate` (scripts/cli/generateStylexTokenFiles.ts). DO NOT EDIT.

import { type GrafanaTheme2 } from '@grafana/data';

export type ThemeCssVarName =
  | '--gf-colors-border-weak'
  | '--gf-colors-border-medium'
  | '--gf-colors-border-strong'
  | '--gf-colors-text-primary'
  | '--gf-colors-text-secondary'
  | '--gf-colors-text-disabled'
  | '--gf-colors-text-link'
  | '--gf-colors-text-max-contrast'
  | '--gf-colors-primary-main'
  | '--gf-colors-primary-text'
  | '--gf-colors-primary-border'
  | '--gf-colors-primary-shade'
  | '--gf-colors-primary-transparent'
  | '--gf-colors-primary-contrast-text'
  | '--gf-colors-primary-border-transparent'
  | '--gf-colors-secondary-main'
  | '--gf-colors-secondary-shade'
  | '--gf-colors-secondary-transparent'
  | '--gf-colors-secondary-text'
  | '--gf-colors-secondary-contrast-text'
  | '--gf-colors-secondary-border'
  | '--gf-colors-secondary-border-transparent'
  | '--gf-colors-info-main'
  | '--gf-colors-info-text'
  | '--gf-colors-info-border'
  | '--gf-colors-info-shade'
  | '--gf-colors-info-transparent'
  | '--gf-colors-info-contrast-text'
  | '--gf-colors-info-border-transparent'
  | '--gf-colors-error-main'
  | '--gf-colors-error-text'
  | '--gf-colors-error-border'
  | '--gf-colors-error-shade'
  | '--gf-colors-error-transparent'
  | '--gf-colors-error-contrast-text'
  | '--gf-colors-error-border-transparent'
  | '--gf-colors-success-main'
  | '--gf-colors-success-text'
  | '--gf-colors-success-border'
  | '--gf-colors-success-shade'
  | '--gf-colors-success-transparent'
  | '--gf-colors-success-contrast-text'
  | '--gf-colors-success-border-transparent'
  | '--gf-colors-warning-main'
  | '--gf-colors-warning-text'
  | '--gf-colors-warning-border'
  | '--gf-colors-warning-shade'
  | '--gf-colors-warning-transparent'
  | '--gf-colors-warning-contrast-text'
  | '--gf-colors-warning-border-transparent'
  | '--gf-colors-background-canvas'
  | '--gf-colors-background-primary'
  | '--gf-colors-background-secondary'
  | '--gf-colors-background-elevated'
  | '--gf-colors-action-hover'
  | '--gf-colors-action-selected'
  | '--gf-colors-action-selected-border'
  | '--gf-colors-action-focus'
  | '--gf-colors-action-hover-opacity'
  | '--gf-colors-action-disabled-text'
  | '--gf-colors-action-disabled-background'
  | '--gf-colors-action-disabled-opacity'
  | '--gf-colors-gradients-brand-horizontal'
  | '--gf-colors-gradients-brand-vertical'
  | '--gf-colors-scrollbar'
  | '--gf-spacing-grid-size'
  | '--gf-spacing-x0'
  | '--gf-spacing-x0-25'
  | '--gf-spacing-x0-5'
  | '--gf-spacing-x1'
  | '--gf-spacing-x1-5'
  | '--gf-spacing-x2'
  | '--gf-spacing-x2-5'
  | '--gf-spacing-x3'
  | '--gf-spacing-x4'
  | '--gf-spacing-x5'
  | '--gf-spacing-x6'
  | '--gf-spacing-x8'
  | '--gf-spacing-x10'
  | '--gf-shape-radius-default'
  | '--gf-shape-radius-md'
  | '--gf-shape-radius-sm'
  | '--gf-shape-radius-lg'
  | '--gf-shape-radius-pill'
  | '--gf-shape-radius-circle'
  | '--gf-typography-html-font-size'
  | '--gf-typography-font-family'
  | '--gf-typography-font-family-monospace'
  | '--gf-typography-font-size'
  | '--gf-typography-font-weight-light'
  | '--gf-typography-font-weight-regular'
  | '--gf-typography-font-weight-medium'
  | '--gf-typography-font-weight-bold'
  | '--gf-typography-size-base'
  | '--gf-typography-size-xs'
  | '--gf-typography-size-sm'
  | '--gf-typography-size-md'
  | '--gf-typography-size-lg'
  | '--gf-typography-h1-font-family'
  | '--gf-typography-h1-font-weight'
  | '--gf-typography-h1-font-size'
  | '--gf-typography-h1-line-height'
  | '--gf-typography-h1-letter-spacing'
  | '--gf-typography-h2-font-family'
  | '--gf-typography-h2-font-weight'
  | '--gf-typography-h2-font-size'
  | '--gf-typography-h2-line-height'
  | '--gf-typography-h2-letter-spacing'
  | '--gf-typography-h3-font-family'
  | '--gf-typography-h3-font-weight'
  | '--gf-typography-h3-font-size'
  | '--gf-typography-h3-line-height'
  | '--gf-typography-h3-letter-spacing'
  | '--gf-typography-h4-font-family'
  | '--gf-typography-h4-font-weight'
  | '--gf-typography-h4-font-size'
  | '--gf-typography-h4-line-height'
  | '--gf-typography-h4-letter-spacing'
  | '--gf-typography-h5-font-family'
  | '--gf-typography-h5-font-weight'
  | '--gf-typography-h5-font-size'
  | '--gf-typography-h5-line-height'
  | '--gf-typography-h5-letter-spacing'
  | '--gf-typography-h6-font-family'
  | '--gf-typography-h6-font-weight'
  | '--gf-typography-h6-font-size'
  | '--gf-typography-h6-line-height'
  | '--gf-typography-h6-letter-spacing'
  | '--gf-typography-body-font-family'
  | '--gf-typography-body-font-weight'
  | '--gf-typography-body-font-size'
  | '--gf-typography-body-line-height'
  | '--gf-typography-body-letter-spacing'
  | '--gf-typography-body-small-font-family'
  | '--gf-typography-body-small-font-weight'
  | '--gf-typography-body-small-font-size'
  | '--gf-typography-body-small-line-height'
  | '--gf-typography-body-small-letter-spacing'
  | '--gf-typography-code-font-family'
  | '--gf-typography-code-font-weight'
  | '--gf-typography-code-font-size'
  | '--gf-typography-code-line-height'
  | '--gf-typography-code-letter-spacing'
  | '--gf-shadows-z1'
  | '--gf-shadows-z2'
  | '--gf-shadows-z3'
  | '--gf-components-height-sm'
  | '--gf-components-height-md'
  | '--gf-components-height-lg'
  | '--gf-components-input-border-color'
  | '--gf-components-input-border-hover'
  | '--gf-components-input-text'
  | '--gf-components-input-background'
  | '--gf-components-panel-padding'
  | '--gf-components-panel-header-height'
  | '--gf-components-panel-background'
  | '--gf-components-panel-border-color'
  | '--gf-components-panel-box-shadow'
  | '--gf-components-dropdown-background'
  | '--gf-components-tooltip-background'
  | '--gf-components-tooltip-text'
  | '--gf-components-dashboard-background'
  | '--gf-components-dashboard-padding'
  | '--gf-components-drawer-padding'
  | '--gf-components-overlay-background'
  | '--gf-components-sidemenu-width'
  | '--gf-components-menu-tabs-height'
  | '--gf-components-text-highlight-text'
  | '--gf-components-text-highlight-background'
  | '--gf-components-horizontal-drawer-default-height'
  | '--gf-components-table-row-hover-background'
  | '--gf-components-table-row-selected'
  | '--gf-components-menu-padding'
  | '--gf-v1-palette-gray98'
  | '--gf-v1-palette-gray97'
  | '--gf-v1-palette-gray95'
  | '--gf-v1-palette-gray90'
  | '--gf-v1-palette-gray85'
  | '--gf-v1-palette-gray70'
  | '--gf-v1-palette-gray60'
  | '--gf-v1-palette-gray33'
  | '--gf-v1-palette-gray25'
  | '--gf-v1-palette-gray15'
  | '--gf-v1-palette-gray10'
  | '--gf-v1-palette-gray05'
  | '--gf-v1-palette-blue95'
  | '--gf-v1-palette-blue85'
  | '--gf-v1-palette-blue80'
  | '--gf-v1-palette-blue77'
  | '--gf-v1-palette-red88'
  | '--gf-v1-palette-black'
  | '--gf-v1-palette-white'
  | '--gf-v1-palette-dark1'
  | '--gf-v1-palette-dark2'
  | '--gf-v1-palette-dark3'
  | '--gf-v1-palette-dark4'
  | '--gf-v1-palette-dark5'
  | '--gf-v1-palette-dark6'
  | '--gf-v1-palette-dark7'
  | '--gf-v1-palette-dark8'
  | '--gf-v1-palette-dark9'
  | '--gf-v1-palette-dark10'
  | '--gf-v1-palette-gray1'
  | '--gf-v1-palette-gray2'
  | '--gf-v1-palette-gray3'
  | '--gf-v1-palette-gray4'
  | '--gf-v1-palette-gray5'
  | '--gf-v1-palette-gray6'
  | '--gf-v1-palette-gray7'
  | '--gf-v1-palette-red-base'
  | '--gf-v1-palette-red-shade'
  | '--gf-v1-palette-green-base'
  | '--gf-v1-palette-green-shade'
  | '--gf-v1-palette-red'
  | '--gf-v1-palette-yellow'
  | '--gf-v1-palette-purple'
  | '--gf-v1-palette-variable'
  | '--gf-v1-palette-orange'
  | '--gf-v1-palette-orange-dark'
  | '--gf-v1-palette-brand-primary'
  | '--gf-v1-palette-brand-success'
  | '--gf-v1-palette-brand-warning'
  | '--gf-v1-palette-brand-danger'
  | '--gf-v1-palette-query-red'
  | '--gf-v1-palette-query-green'
  | '--gf-v1-palette-query-purple'
  | '--gf-v1-palette-query-orange'
  | '--gf-v1-palette-online'
  | '--gf-v1-palette-warn'
  | '--gf-v1-palette-critical';

// Theme paths of every token, space-separated to keep the bundle small. Read dynamically because some
// theme values exist at runtime without being part of the GrafanaTheme2 type.
const TOKEN_PATHS =
  'colors.border.weak colors.border.medium colors.border.strong colors.text.primary ' +
  'colors.text.secondary colors.text.disabled colors.text.link colors.text.maxContrast ' +
  'colors.primary.main colors.primary.text colors.primary.border colors.primary.shade ' +
  'colors.primary.transparent colors.primary.contrastText colors.primary.borderTransparent ' +
  'colors.secondary.main colors.secondary.shade colors.secondary.transparent colors.secondary.text ' +
  'colors.secondary.contrastText colors.secondary.border colors.secondary.borderTransparent ' +
  'colors.info.main colors.info.text colors.info.border colors.info.shade colors.info.transparent ' +
  'colors.info.contrastText colors.info.borderTransparent colors.error.main colors.error.text ' +
  'colors.error.border colors.error.shade colors.error.transparent colors.error.contrastText ' +
  'colors.error.borderTransparent colors.success.main colors.success.text colors.success.border ' +
  'colors.success.shade colors.success.transparent colors.success.contrastText ' +
  'colors.success.borderTransparent colors.warning.main colors.warning.text colors.warning.border ' +
  'colors.warning.shade colors.warning.transparent colors.warning.contrastText ' +
  'colors.warning.borderTransparent colors.background.canvas colors.background.primary ' +
  'colors.background.secondary colors.background.elevated colors.action.hover colors.action.selected ' +
  'colors.action.selectedBorder colors.action.focus colors.action.hoverOpacity ' +
  'colors.action.disabledText colors.action.disabledBackground colors.action.disabledOpacity ' +
  'colors.gradients.brandHorizontal colors.gradients.brandVertical colors.scrollbar spacing.gridSize ' +
  'spacing.x0 spacing.x0_25 spacing.x0_5 spacing.x1 spacing.x1_5 spacing.x2 spacing.x2_5 spacing.x3 ' +
  'spacing.x4 spacing.x5 spacing.x6 spacing.x8 spacing.x10 shape.radius.default shape.radius.md ' +
  'shape.radius.sm shape.radius.lg shape.radius.pill shape.radius.circle typography.htmlFontSize ' +
  'typography.fontFamily typography.fontFamilyMonospace typography.fontSize typography.fontWeightLight ' +
  'typography.fontWeightRegular typography.fontWeightMedium typography.fontWeightBold ' +
  'typography.size.base typography.size.xs typography.size.sm typography.size.md typography.size.lg ' +
  'typography.h1.fontFamily typography.h1.fontWeight typography.h1.fontSize typography.h1.lineHeight ' +
  'typography.h1.letterSpacing typography.h2.fontFamily typography.h2.fontWeight typography.h2.fontSize ' +
  'typography.h2.lineHeight typography.h2.letterSpacing typography.h3.fontFamily ' +
  'typography.h3.fontWeight typography.h3.fontSize typography.h3.lineHeight typography.h3.letterSpacing ' +
  'typography.h4.fontFamily typography.h4.fontWeight typography.h4.fontSize typography.h4.lineHeight ' +
  'typography.h4.letterSpacing typography.h5.fontFamily typography.h5.fontWeight typography.h5.fontSize ' +
  'typography.h5.lineHeight typography.h5.letterSpacing typography.h6.fontFamily ' +
  'typography.h6.fontWeight typography.h6.fontSize typography.h6.lineHeight typography.h6.letterSpacing ' +
  'typography.body.fontFamily typography.body.fontWeight typography.body.fontSize ' +
  'typography.body.lineHeight typography.body.letterSpacing typography.bodySmall.fontFamily ' +
  'typography.bodySmall.fontWeight typography.bodySmall.fontSize typography.bodySmall.lineHeight ' +
  'typography.bodySmall.letterSpacing typography.code.fontFamily typography.code.fontWeight ' +
  'typography.code.fontSize typography.code.lineHeight typography.code.letterSpacing shadows.z1 ' +
  'shadows.z2 shadows.z3 components.height.sm components.height.md components.height.lg ' +
  'components.input.borderColor components.input.borderHover components.input.text ' +
  'components.input.background components.panel.padding components.panel.headerHeight ' +
  'components.panel.background components.panel.borderColor components.panel.boxShadow ' +
  'components.dropdown.background components.tooltip.background components.tooltip.text ' +
  'components.dashboard.background components.dashboard.padding components.drawer.padding ' +
  'components.overlay.background components.sidemenu.width components.menuTabs.height ' +
  'components.textHighlight.text components.textHighlight.background ' +
  'components.horizontalDrawer.defaultHeight components.table.rowHoverBackground ' +
  'components.table.rowSelected components.menu.padding v1.palette.gray98 v1.palette.gray97 ' +
  'v1.palette.gray95 v1.palette.gray90 v1.palette.gray85 v1.palette.gray70 v1.palette.gray60 ' +
  'v1.palette.gray33 v1.palette.gray25 v1.palette.gray15 v1.palette.gray10 v1.palette.gray05 ' +
  'v1.palette.blue95 v1.palette.blue85 v1.palette.blue80 v1.palette.blue77 v1.palette.red88 ' +
  'v1.palette.black v1.palette.white v1.palette.dark1 v1.palette.dark2 v1.palette.dark3 v1.palette.dark4 ' +
  'v1.palette.dark5 v1.palette.dark6 v1.palette.dark7 v1.palette.dark8 v1.palette.dark9 ' +
  'v1.palette.dark10 v1.palette.gray1 v1.palette.gray2 v1.palette.gray3 v1.palette.gray4 ' +
  'v1.palette.gray5 v1.palette.gray6 v1.palette.gray7 v1.palette.redBase v1.palette.redShade ' +
  'v1.palette.greenBase v1.palette.greenShade v1.palette.red v1.palette.yellow v1.palette.purple ' +
  'v1.palette.variable v1.palette.orange v1.palette.orangeDark v1.palette.brandPrimary ' +
  'v1.palette.brandSuccess v1.palette.brandWarning v1.palette.brandDanger v1.palette.queryRed ' +
  'v1.palette.queryGreen v1.palette.queryPurple v1.palette.queryOrange v1.palette.online v1.palette.warn ' +
  'v1.palette.critical';
const PX_PATHS = new Set(['spacing.gridSize', 'typography.fontSize', 'typography.htmlFontSize']);

const kebab = (key: string) =>
  key
    .replace(/_/g, '-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();

function isThemeCssVarName(name: string): name is ThemeCssVarName {
  return name.startsWith('--gf-');
}

function readPath(theme: GrafanaTheme2, path: string[]): unknown {
  let value: unknown = theme;
  for (const key of path) {
    if ((typeof value !== 'object' && typeof value !== 'function') || value === null) {
      return undefined;
    }
    value = Reflect.get(value, key);
  }
  return value;
}

/**
 * Maps a theme to the `--gf-*` custom properties declared in tokens.stylex.ts. A value the theme omits
 * (e.g. letterSpacing for non-default fonts) maps to `initial`, the guaranteed-invalid value, so the
 * property using it computes to `unset`, just like Emotion omitting the declaration.
 */
export function themeToCssVars(theme: GrafanaTheme2): Partial<Record<ThemeCssVarName, string>> {
  const vars: Partial<Record<ThemeCssVarName, string>> = {};
  for (const dotted of TOKEN_PATHS.split(' ')) {
    const path = dotted.split('.');
    const name = `--gf-${path.map(kebab).join('-')}`;
    const value = readPath(theme, path);
    if (isThemeCssVarName(name)) {
      vars[name] =
        value === undefined || value === null ? 'initial' : PX_PATHS.has(dotted) ? `${value}px` : String(value);
    }
  }
  return vars;
}
