import * as stylex from '@stylexjs/stylex';

/**
 * StyleX handles for the theme CSS variables emitted by `getThemeCssVariables` (see `cssVariables.ts`).
 * Keys starting with `--` keep their literal name, so `colors['--grafana-colors-border-weak']` compiles to
 * `var(--grafana-colors-border-weak)`. Values are supplied at runtime from the active `GrafanaTheme2` by
 * `useThemeCssVariables`; `initial` is only the unset placeholder. Keep in sync with `cssVariables.ts`
 * (enforced by `cssVariables.test.ts`).
 */

export const colors = stylex.defineVars({
  '--grafana-colors-primary-main': 'initial',
  '--grafana-colors-primary-shade': 'initial',
  '--grafana-colors-primary-text': 'initial',
  '--grafana-colors-primary-border': 'initial',
  '--grafana-colors-primary-transparent': 'initial',
  '--grafana-colors-primary-border-transparent': 'initial',
  '--grafana-colors-primary-contrast-text': 'initial',
  '--grafana-colors-secondary-main': 'initial',
  '--grafana-colors-secondary-shade': 'initial',
  '--grafana-colors-secondary-text': 'initial',
  '--grafana-colors-secondary-border': 'initial',
  '--grafana-colors-secondary-transparent': 'initial',
  '--grafana-colors-secondary-border-transparent': 'initial',
  '--grafana-colors-secondary-contrast-text': 'initial',
  '--grafana-colors-info-main': 'initial',
  '--grafana-colors-info-shade': 'initial',
  '--grafana-colors-info-text': 'initial',
  '--grafana-colors-info-border': 'initial',
  '--grafana-colors-info-transparent': 'initial',
  '--grafana-colors-info-border-transparent': 'initial',
  '--grafana-colors-info-contrast-text': 'initial',
  '--grafana-colors-error-main': 'initial',
  '--grafana-colors-error-shade': 'initial',
  '--grafana-colors-error-text': 'initial',
  '--grafana-colors-error-border': 'initial',
  '--grafana-colors-error-transparent': 'initial',
  '--grafana-colors-error-border-transparent': 'initial',
  '--grafana-colors-error-contrast-text': 'initial',
  '--grafana-colors-success-main': 'initial',
  '--grafana-colors-success-shade': 'initial',
  '--grafana-colors-success-text': 'initial',
  '--grafana-colors-success-border': 'initial',
  '--grafana-colors-success-transparent': 'initial',
  '--grafana-colors-success-border-transparent': 'initial',
  '--grafana-colors-success-contrast-text': 'initial',
  '--grafana-colors-warning-main': 'initial',
  '--grafana-colors-warning-shade': 'initial',
  '--grafana-colors-warning-text': 'initial',
  '--grafana-colors-warning-border': 'initial',
  '--grafana-colors-warning-transparent': 'initial',
  '--grafana-colors-warning-border-transparent': 'initial',
  '--grafana-colors-warning-contrast-text': 'initial',
  '--grafana-colors-text-primary': 'initial',
  '--grafana-colors-text-secondary': 'initial',
  '--grafana-colors-text-disabled': 'initial',
  '--grafana-colors-text-link': 'initial',
  '--grafana-colors-text-max-contrast': 'initial',
  '--grafana-colors-background-canvas': 'initial',
  '--grafana-colors-background-primary': 'initial',
  '--grafana-colors-background-secondary': 'initial',
  '--grafana-colors-background-elevated': 'initial',
  '--grafana-colors-border-weak': 'initial',
  '--grafana-colors-border-medium': 'initial',
  '--grafana-colors-border-strong': 'initial',
  '--grafana-colors-gradients-brand-horizontal': 'initial',
  '--grafana-colors-gradients-brand-vertical': 'initial',
  '--grafana-colors-action-hover': 'initial',
  '--grafana-colors-action-selected': 'initial',
  '--grafana-colors-action-selected-border': 'initial',
  '--grafana-colors-action-focus': 'initial',
  '--grafana-colors-action-hover-opacity': 'initial',
  '--grafana-colors-action-disabled-text': 'initial',
  '--grafana-colors-action-disabled-background': 'initial',
  '--grafana-colors-action-disabled-opacity': 'initial',
  '--grafana-v1-palette-gray98': 'initial',
});

export const spacing = stylex.defineVars({
  '--grafana-spacing-grid-size': 'initial',
  '--grafana-spacing-0': 'initial',
  '--grafana-spacing-0-25': 'initial',
  '--grafana-spacing-0-5': 'initial',
  '--grafana-spacing-1': 'initial',
  '--grafana-spacing-1-5': 'initial',
  '--grafana-spacing-2': 'initial',
  '--grafana-spacing-2-5': 'initial',
  '--grafana-spacing-3': 'initial',
  '--grafana-spacing-4': 'initial',
  '--grafana-spacing-5': 'initial',
  '--grafana-spacing-6': 'initial',
  '--grafana-spacing-8': 'initial',
  '--grafana-spacing-10': 'initial',
});

export const shape = stylex.defineVars({
  '--grafana-shape-radius-default': 'initial',
  '--grafana-shape-radius-md': 'initial',
  '--grafana-shape-radius-sm': 'initial',
  '--grafana-shape-radius-lg': 'initial',
  '--grafana-shape-radius-pill': 'initial',
  '--grafana-shape-radius-circle': 'initial',
});

export const typography = stylex.defineVars({
  '--grafana-typography-font-family': 'initial',
  '--grafana-typography-font-family-monospace': 'initial',
  '--grafana-typography-font-size': 'initial',
  '--grafana-typography-font-weight-light': 'initial',
  '--grafana-typography-font-weight-regular': 'initial',
  '--grafana-typography-font-weight-medium': 'initial',
  '--grafana-typography-font-weight-bold': 'initial',
  '--grafana-typography-size-base': 'initial',
  '--grafana-typography-size-xs': 'initial',
  '--grafana-typography-size-sm': 'initial',
  '--grafana-typography-size-md': 'initial',
  '--grafana-typography-size-lg': 'initial',
  '--grafana-typography-body-font-size': 'initial',
  '--grafana-typography-body-font-weight': 'initial',
  '--grafana-typography-body-line-height': 'initial',
  '--grafana-typography-body-font-family': 'initial',
  '--grafana-typography-body-letter-spacing': 'initial',
  '--grafana-typography-body-small-font-size': 'initial',
  '--grafana-typography-body-small-font-weight': 'initial',
  '--grafana-typography-body-small-line-height': 'initial',
  '--grafana-typography-body-small-font-family': 'initial',
  '--grafana-typography-body-small-letter-spacing': 'initial',
  '--grafana-typography-code-font-size': 'initial',
  '--grafana-typography-code-font-weight': 'initial',
  '--grafana-typography-code-line-height': 'initial',
  '--grafana-typography-code-font-family': 'initial',
  '--grafana-typography-code-letter-spacing': 'initial',
});

export const shadows = stylex.defineVars({
  '--grafana-shadows-z1': 'initial',
  '--grafana-shadows-z2': 'initial',
  '--grafana-shadows-z3': 'initial',
});
