import { writeFile } from 'node:fs/promises';
import { resolve } from 'path';

import { createTheme, type GrafanaTheme2 } from '@grafana/data';

// Piped into node by `yarn themes-generate`, so __dirname is the repo root.
const outDir = resolve(__dirname, 'packages', 'grafana-ui', 'src', 'themes', 'stylex');

const HEADER = `// Code generated by \`yarn themes-generate\` (scripts/cli/generateStylexTokenFiles.ts). DO NOT EDIT.\n`;

/** Top-level theme groups that become `defineVars` groups, in output order. */
const VAR_GROUPS = ['colors', 'spacing', 'shape', 'typography', 'shadows', 'components', 'v1'] as const;
type VarGroup = (typeof VAR_GROUPS)[number];

/** Only these subtrees of a group are emitted (whole group when absent). */
const GROUP_INCLUDES: Partial<Record<VarGroup, string[][]>> = {
  v1: [['v1', 'palette']],
};

/** Leaves that are not CSS values. */
const EXCLUDED_PATHS = [
  'colors.mode',
  'colors.whiteBase',
  'colors.contrastThreshold',
  'colors.hoverFactor',
  'colors.tonalOffset',
  'components.menu.borderRadius',
];
const EXCLUDED_LEAF_KEYS = new Set(['name']);

/** Numeric leaves that Emotion serialises with a `px` unit. Every other number is emitted unitless. */
const PX_NUMBER_PATHS = new Set(['spacing.gridSize', 'typography.fontSize', 'typography.htmlFontSize']);

interface TokenLeaf {
  path: string[];
  varName: string;
  kind: 'string' | 'px' | 'number';
}

const kebab = (s: string) =>
  s
    .replace(/_/g, '-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase();

const toVarName = (path: string[]) => `--gf-${path.map(kebab).join('-')}`;

function collectLeaves(group: VarGroup, theme: GrafanaTheme2): TokenLeaf[] {
  const leaves: TokenLeaf[] = [];
  const includes = GROUP_INCLUDES[group];

  const walk = (value: unknown, path: string[]) => {
    const dotted = path.join('.');
    if (EXCLUDED_PATHS.includes(dotted)) {
      return;
    }
    if (typeof value === 'string' || typeof value === 'number') {
      if (EXCLUDED_LEAF_KEYS.has(path[path.length - 1])) {
        return;
      }
      if (includes && !includes.some((prefix) => prefix.every((p, i) => path[i] === p))) {
        return;
      }
      const kind = typeof value === 'string' ? 'string' : PX_NUMBER_PATHS.has(dotted) ? 'px' : 'number';
      leaves.push({ path, varName: toVarName(path), kind });
      return;
    }
    // theme.spacing is a function with token properties attached.
    if ((typeof value === 'object' && value !== null && !Array.isArray(value)) || typeof value === 'function') {
      for (const key of Object.keys(value)) {
        walk(Reflect.get(value, key), [...path, key]);
      }
    }
  };

  walk(Reflect.get(theme, group), [group]);

  const seen = new Set<string>();
  for (const leaf of leaves) {
    if (seen.has(leaf.varName)) {
      throw new Error(`Duplicate StyleX token name ${leaf.varName}`);
    }
    seen.add(leaf.varName);
  }
  return leaves;
}

function readLeaf(theme: GrafanaTheme2, leaf: TokenLeaf): string {
  let value: unknown = theme;
  for (const key of leaf.path) {
    value = typeof value === 'object' || typeof value === 'function' ? Reflect.get(Object(value), key) : undefined;
  }
  return leaf.kind === 'px' ? `${value}px` : String(value);
}

function tokensFile(theme: GrafanaTheme2, groups: Record<VarGroup, TokenLeaf[]>) {
  let out = `${HEADER}\n`;
  out += `// Defaults are the dark theme (the ThemeContext default). Real values are written at runtime from the\n`;
  out += `// active GrafanaTheme2 by GlobalStyles / ScopedThemeVars, so every built-in and custom theme works.\n`;
  out += `import * as stylex from '@stylexjs/stylex';\n`;
  for (const group of VAR_GROUPS) {
    out += `\nexport const ${group} = stylex.defineVars({\n`;
    for (const leaf of groups[group]) {
      out += `  '${leaf.varName}': ${JSON.stringify(readLeaf(theme, leaf))},\n`;
    }
    out += `});\n`;
  }
  return out;
}

function cssVarsFile(groups: Record<VarGroup, TokenLeaf[]>) {
  const all = VAR_GROUPS.flatMap((g) => groups[g]);
  let out = `${HEADER}\n`;
  out += `import { type GrafanaTheme2 } from '@grafana/data';\n\n`;
  out += `export type ThemeCssVarName =\n${all.map((l) => `  | '${l.varName}'`).join('\n')};\n\n`;
  out += `// [var name, theme path, serialisation]. Paths are read dynamically because some theme values exist at\n`;
  out += `// runtime without being part of the GrafanaTheme2 type.\n`;
  out += `const TOKENS: Array<[ThemeCssVarName, string[], 'string' | 'px' | 'number']> = [\n`;
  for (const leaf of all) {
    out += `  ['${leaf.varName}', ${JSON.stringify(leaf.path)}, '${leaf.kind}'],\n`;
  }
  out += `];\n\n`;
  out += `function readPath(theme: GrafanaTheme2, path: string[]): unknown {\n`;
  out += `  let value: unknown = theme;\n`;
  out += `  for (const key of path) {\n`;
  out += `    if ((typeof value !== 'object' && typeof value !== 'function') || value === null) {\n`;
  out += `      return undefined;\n`;
  out += `    }\n`;
  out += `    value = Reflect.get(value, key);\n`;
  out += `  }\n`;
  out += `  return value;\n`;
  out += `}\n\n`;
  out += `/**\n * Maps a theme to the \`--gf-*\` custom properties declared in tokens.stylex.ts. A value the theme omits\n * (e.g. letterSpacing for non-default fonts) maps to \`initial\`, the guaranteed-invalid value, so the\n * property using it computes to \`unset\`, just like Emotion omitting the declaration.\n */\n`;
  out += `export function themeToCssVars(theme: GrafanaTheme2): Partial<Record<ThemeCssVarName, string>> {\n`;
  out += `  const vars: Partial<Record<ThemeCssVarName, string>> = {};\n`;
  out += `  for (const [name, path, kind] of TOKENS) {\n`;
  out += `    const value = readPath(theme, path);\n`;
  out += `    vars[name] = value === undefined || value === null ? 'initial' : kind === 'px' ? \`\${value}px\` : String(value);\n`;
  out += `  }\n`;
  out += `  return vars;\n`;
  out += `}\n`;
  return out;
}

function constantsFile(theme: GrafanaTheme2) {
  const { breakpoints, transitions, zIndex } = theme;
  const bp: Record<string, string> = {};
  for (const key of breakpoints.keys) {
    bp[`${key}Up`] = breakpoints.up(key);
  }
  for (const key of breakpoints.keys) {
    bp[`${key}Down`] = breakpoints.down(key);
  }
  const motion = {
    noPreference: transitions.handleMotion('no-preference'),
    reduce: transitions.handleMotion('reduce'),
    noPreferenceOrReduce: transitions.handleMotion('no-preference', 'reduce'),
  };
  const durations = Object.fromEntries(Object.entries(transitions.duration).map(([k, v]) => [k, `${v}ms`]));

  const block = (name: string, doc: string, values: Record<string, string | number>) =>
    `\n/** ${doc} */\nexport const ${name} = stylex.defineConsts({\n${Object.entries(values)
      .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
      .join('\n')}\n});\n`;

  let out = `${HEADER}\n`;
  out += `// Theme values that never vary between themes. Generated from createBreakpoints/createTransitions so\n`;
  out += `// the emitted strings are byte-identical to what Emotion produced.\n`;
  out += `import * as stylex from '@stylexjs/stylex';\n`;
  out += block('bp', '`theme.breakpoints.up(key)` → `bp.<key>Up`, `theme.breakpoints.down(key)` → `bp.<key>Down`.', bp);
  out += block('motion', "`theme.transitions.handleMotion('no-preference')` → `motion.noPreference`, etc.", motion);
  out += block('durations', '`theme.transitions.duration.<key>` as a CSS time.', durations);
  out += block('easings', '`theme.transitions.easing.<key>`.', { ...transitions.easing });
  out += block('zIndex', '`theme.zIndex.<key>`.', { ...zIndex });
  return out;
}

async function generateStylexTokenFiles() {
  const theme = createTheme();
  const groups: Record<VarGroup, TokenLeaf[]> = {
    colors: collectLeaves('colors', theme),
    spacing: collectLeaves('spacing', theme),
    shape: collectLeaves('shape', theme),
    typography: collectLeaves('typography', theme),
    shadows: collectLeaves('shadows', theme),
    components: collectLeaves('components', theme),
    v1: collectLeaves('v1', theme),
  };
  try {
    await writeFile(resolve(outDir, 'tokens.stylex.ts'), tokensFile(theme, groups));
    await writeFile(resolve(outDir, 'constants.stylex.ts'), constantsFile(theme));
    await writeFile(resolve(outDir, 'themeToCssVars.ts'), cssVarsFile(groups));
  } catch (error) {
    console.error('\nWriting StyleX token files failed', error);
    process.exit(1);
  }
}

generateStylexTokenFiles();
