import * as stylex from '@stylexjs/stylex';

import { grafanaTokens } from '@grafana/ui/unstable';

export const callTreeContainerStyles = stylex.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: grafanaTokens.colors_background_primary,
    display: 'flex',
    flexDirection: 'column',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    paddingTop: grafanaTokens.spacing_x1,
    paddingBottom: grafanaTokens.spacing_x1,
    gap: grafanaTokens.spacing_x1,
    flexWrap: 'wrap',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: grafanaTokens.colors_border_weak,
    ':not(:has(> :not(:empty)))': {
      display: 'none',
    },
  },
  toolbarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: grafanaTokens.spacing_x1,
  },
  searchContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: grafanaTokens.spacing_x1,
    flexWrap: 'wrap',
  },
  searchNavigation: {
    display: 'flex',
    alignItems: 'center',
    gap: grafanaTokens.spacing_x0_5,
    paddingLeft: grafanaTokens.spacing_x1,
    paddingRight: grafanaTokens.spacing_x1,
  },
  searchCounter: {
    fontSize: grafanaTokens.typography_bodySmall_fontSize,
    color: grafanaTokens.colors_text_secondary,
    whiteSpace: 'nowrap',
  },
  searchNoResults: {
    fontSize: grafanaTokens.typography_bodySmall_fontSize,
    color: grafanaTokens.colors_text_secondary,
    fontStyle: 'italic',
  },
  searchError: {
    fontSize: grafanaTokens.typography_bodySmall_fontSize,
    color: grafanaTokens.colors_error_text,
  },
  actionsCell: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '20px',
  },
  valueCell: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    fontVariantNumeric: 'tabular-nums',
    height: '20px',
  },
  valueNumber: {
    flex: '1 1 auto',
    textAlign: 'right',
    whiteSpace: 'nowrap',
    minWidth: '60px',
  },
  percentNumber: {
    flex: '0 0 60px',
    width: '60px',
    textAlign: 'right',
    color: grafanaTokens.colors_text_secondary,
    whiteSpace: 'nowrap',
  },
  focusedItem: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: grafanaTokens.colors_background_secondary,
    borderRadius: grafanaTokens.shape_radius_default,
    paddingTop: grafanaTokens.spacing_x0_5,
    paddingBottom: grafanaTokens.spacing_x0_5,
    paddingLeft: grafanaTokens.spacing_x1,
    paddingRight: grafanaTokens.spacing_x1,
    fontSize: grafanaTokens.typography_bodySmall_fontSize,
    fontWeight: grafanaTokens.typography_fontWeightMedium,
    lineHeight: grafanaTokens.typography_bodySmall_lineHeight,
    color: grafanaTokens.colors_text_secondary,
  },
  focusedItemLabel: {
    maxWidth: '200px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginLeft: grafanaTokens.spacing_x0_5,
  },
  callersItem: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: grafanaTokens.colors_background_secondary,
    borderRadius: grafanaTokens.shape_radius_default,
    paddingTop: grafanaTokens.spacing_x0_5,
    paddingBottom: grafanaTokens.spacing_x0_5,
    paddingLeft: grafanaTokens.spacing_x1,
    paddingRight: grafanaTokens.spacing_x1,
    fontSize: grafanaTokens.typography_bodySmall_fontSize,
    fontWeight: grafanaTokens.typography_fontWeightMedium,
    lineHeight: grafanaTokens.typography_bodySmall_lineHeight,
    color: grafanaTokens.colors_text_secondary,
  },
  callersItemLabel: {
    maxWidth: '200px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginLeft: grafanaTokens.spacing_x0_5,
  },
  modePillCloseButton: {
    verticalAlign: 'text-bottom',
    marginTop: grafanaTokens.spacing_x0,
    marginBottom: grafanaTokens.spacing_x0,
    marginLeft: grafanaTokens.spacing_x0_5,
    marginRight: grafanaTokens.spacing_x0_5,
  },
});
